### ISSUE TITLE
Similarity Splitters drop Structures

### ISSUE THREAD

**Issue by luiswyss** [cgoliver/rnaglib#13]
I fixed up some code for similarity splitting and noticed that the splitters don't return all the rnas that they receive as input. 

_len(ds) > len(train) + len(val) + len(test)_

This is the case for both RNAAlign and CDhit albeit to different extent.

Minimal code:
```
from rnaglib.splitters import CDHitSplitter
from rnaglib.data_loading import RNADataset

ds = RNADataset(debug=True)
train, val, test = CDHitSplitter(similarity_threshold=.5)(ds) #use RNAalignSplitter to test the other case
len(train) + len(test) + len(val) # <101
```

I don't quite understand how the code works but `keep_dataset` implies that this is at least partially intentional.
@cgoliver could you please elaborate how this is to be understood?

Many thanks!

**Comment by cgoliver** [comment]
Yes this happens in the case that the aligners drop some pairs for their own reasons (maybe length constraints?).

[this](https://github.com/cgoliver/rnaglib/blob/c30856c454dace483f3f8b83544d69204e4ef1d1/src/rnaglib/splitters/similarity_splitter.py#L129) is where they get filtered out.

So the final list of indices for each split is a subset of the original dataset's indices.

Perhaps we can have a warning when the subset is smaller than the whole..

**Comment by cgoliver** [comment]
Added a warning when dataset size not equal to sum of splits.
