### ISSUE TITLE
Loading tasks from root dir broken

### ISSUE THREAD

**Issue by luiswyss** [cgoliver/rnaglib#21]
Loading tasks from a root directory fails due to indexing issues.

Here a minimal reproducible example:
```
"Loading tasks from root fails"
from rnaglib.tasks import ChemicalModification

#This works (root folder is created)
task = ChemicalModification(root="loadbugroot", debug=True)

#This does not (loading from existing root folder
task2 = ChemicalModification(root="loadbugroot", debug=True)
```

Notes:
* The issue arises irrespective of the task selected.
* The issue only arises irrespective from whether debug is set to True.
* The issue does not arise when recompute is set to True.

**Comment by luiswyss** [comment]
okay, interestingly I cannot always replicate myself either. Investigating

**Comment by luiswyss** [comment]
Checking `loadbugroot/dataset` is empty.
the train and test indices are saved to the root folder but the json files are not written to the dataset dir.

**Comment by cgoliver** [comment]
Hey Luis, I'm on the road ATM. Is it something you are able to patch?

Try having a look at the logic here

https://github.com/cgoliver/rnaglib/blob/e912cb233bbf397ab954806ae5d4509988e1f5bf/src/rnaglib/data_loading/rna_dataset.py#L283

@Vincentx15 should be able to help

**Comment by luiswyss** [comment]
I think I fixed it :)
Let me know if I broke something by accident.

**Comment by cgoliver** [comment]
Would be good if you added a unit test for task loading and dumping
