### ISSUE TITLE
About how to get backbone of RNA uesd in the fr3d_to_graph method

### ISSUE THREAD

**Issue by ghliu521** [cgoliver/rnaglib#6]
Dear carlos,

I've seen the question you proposed in the fr3d repository. Recently I tried and analysed the code on how to convert cif file to graph via fr3d. But I found the method you'v implemented through biopython didn't consider the non-standard residues. However in the RCSB PDB database there may exist non-standard residues because of natural mutations or modifications by human for some reasons. So you may get discontinuous graphs when you apply the  fr3d_to_graph method implemented in the present repository. What's more,  I'v also checked annot_df produced by fr3d and found that the annotation between base pairs do include non-standard residues if there are non-standard residues in the cif file. 

I hope to have a discussion with you on that.

**Comment by cgoliver** [comment]
Hi @ghliu521 ! Thanks for getting in touch. 

Yes I have not had a chance to carefully check the output of that function. Would you have a sample PDB we can focus on to start having a look?

**Comment by ghliu521** [comment]
Hi @cgoliver .You may try 1evv to have a look and check you code.

What I have forgotten to mention before is that although there are not so many non-standard residues, I think it's necessary to consider them when constructing RNA graph. If you don't consider non-standard residues in the get_bb method, you may get a final graph with some  nodes without atrributes. I've finished two ways to solve this bug, one is adding the  non-standard residues in the get_bb method, one is not considering the non-standard residues. 

Look forward to hear from you.

**Comment by cgoliver** [comment]
Yes indeed. Should be an easy fix. The other thing to check is whether fr3d keeps base pairs for non-standard residues. Are you working on a PR?

**Comment by ghliu521** [comment]
> Yes indeed. Should be an easy fix. The other thing to check is whether fr3d keeps base pairs for non-standard residues. Are you working on a PR?

Not Really. If you and your team want me to commit a PR. I'd love to do that.

**Comment by cgoliver** [comment]
I asked because you said you had finished two ways to solve the bug. We are always happy to support contributions so if you feel they are in good shape for a PR please feel free. Otherwise we are planning on addressing the issue ourselves but might take a bit longer. Thanks!

**Comment by ghliu521** [comment]
Hi @cgoliver submit a PR. Please have a look.
